[project]
name = "mcp-server-fdc"
version = "0.1.0"
description = "Python implementation of McpServerFdc"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.1",
    "pydantic",
    "requests",
    "click",
]